Name:           ros-kinetic-message-generation
Version:        0.4.0
Release:        0%{?dist}
Summary:        ROS message_generation package
Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/message_generation
Source0:        %{name}-%{version}.tar.gz
Source1001:     %{name}.manifest
BuildRequires:  gcc-c++
BuildRequires:  ros-kinetic-catkin
Requires:       ros-kinetic-gencpp
Requires:       ros-kinetic-geneus
Requires:       ros-kinetic-gennodejs
Requires:       ros-kinetic-genlisp
Requires:       ros-kinetic-genmsg
Requires:       ros-kinetic-genpy

%description
Package modeling the build-time dependencies for generating language bindings of
messages.

%prep
%setup -q
cp %{SOURCE1001} .

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/usr/setup.sh" ]; then . "/usr/setup.sh"; fi
mkdir build && cd build
cmake .. \
        -DCMAKE_INSTALL_PREFIX="$CMAKE_PREFIX_PATH" \
        -DCMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/usr/setup.sh" ]; then . "/usr/setup.sh"; fi
pushd build
make install DESTDIR=%{buildroot}
popd

%files -f build/install_manifest.txt
%manifest %{name}.manifest
%defattr(-,root,root)

%changelog
* Mon Apr  3 2017 Zhang Xingtao <xingtao.zhang@yahoo.com> - 0.4.0
* Fri May 09 2014 Dirk Thomas <dthomas@osrfoundation.org> - 0.2.10-0
- Autogenerated by Bloom

