Name:           ros-kinetic-message-generation
Version:        0.4.0
Release:        0%{?dist}
Summary:        ROS message_generation package
Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/message_generation
Source0:        %{name}-%{version}.tar.gz
Source1001:     %{name}.manifest
BuildRequires:  gcc-c++
BuildRequires:  ros-kinetic-catkin
Requires:       ros-kinetic-gencpp
Requires:       ros-kinetic-geneus
Requires:       ros-kinetic-gennodejs
Requires:       ros-kinetic-genlisp
Requires:       ros-kinetic-genmsg
Requires:       ros-kinetic-genpy

%description
Package modeling the build-time dependencies for generating language bindings of
messages.

%prep
%setup -q
cp %{SOURCE1001} .

%build
%{__ros_setup}
%{__ros_build}

%install
%{__ros_setup}
%{__ros_install}

%files -f build/install_manifest.txt
%manifest %{name}.manifest
%defattr(-,root,root)

%changelog
* Mon Apr  3 2017 Zhang Xingtao <xingtao.zhang@yahoo.com> - 0.4.0
* Fri May 09 2014 Dirk Thomas <dthomas@osrfoundation.org> - 0.2.10-0
- Autogenerated by Bloom
